### ISSUE TITLE
users no longer have thumbnail view

### ISSUE THREAD

**Issue by ervinj1998** [Hawaiideveloper/Social_Network_Front_end#97]
https://github.com/Hawaiideveloper/Social_Network_Front_end/blob/62d0a67cad4946204c08ed87fa6285d4029c113c/src/user/Users.js#L32

should we add this back in?

renderUsers = (users) => (
    <div className="row">
    {users.map((user, i) => (
       <div className="card col-md-4"  key={i}>
       <img 
                 style={{height: "200px", width: "auto"}}
                 className="img-thumbnail"
                 src={`${process.env.REACT_APP_API_URL}/user/photo/${
                    user._id
                }`}
                onError={i => (i.target.src = `${DefaultProfile}`)}
                 alt={user.name}
            />

**Comment by Hawaiideveloper** [comment]
https://github.com/ervinj1998/Social_Network_Front_end/blob/71fcfc577630b98ef1139266c685b6091bc59cf6/src/user/Users.js#L33


This mentions thumbnails.  

Unsure how we lost this

**Comment by Hawaiideveloper** [comment]
I fixed it, and submitted a PR
https://github.com/Hawaiideveloper/Social_Network_Front_end/pull/98/commits/ecb5721ad8061af45a4d3725f7467c0a84478a24

**Comment by Hawaiideveloper** [comment]
now closing the issue
